import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const GENERATED_HEADER = `/* eslint-disable */
/* This file is auto-generated by pnpm openapi:types:generate. Do not edit manually. */

`;

export async function generateOpenApiTypes(outputPath: string): Promise<void> {
  const outputFilePath = resolve(outputPath);

  const openapiTypescriptModule = await import('openapi-typescript');
  const openapiTypescript = openapiTypescriptModule.default;
  const openapiAst = await openapiTypescript(pathToFileURL(resolve('openapi/openapi.json')), {
    alphabetize: true
  });
  const generatedTypes = openapiTypescriptModule.astToString(openapiAst);

  await mkdir(dirname(outputFilePath), { recursive: true });
  await writeFile(outputFilePath, `${GENERATED_HEADER}${generatedTypes}`, 'utf8');
}

async function main(): Promise<void> {
  const outputPath = process.argv[2] ?? '../frontend/generated/backend-api.types.ts';
  await generateOpenApiTypes(outputPath);
  // eslint-disable-next-line no-console
  console.log(`OpenAPI TypeScript definitions generated at ${resolve(outputPath)}`);
}

if (require.main === module) {
  void main().catch((error) => {
    // eslint-disable-next-line no-console
    console.error('OpenAPI TypeScript generation failed:', error);
    process.exitCode = 1;
  });
}
