import { Transform } from 'class-transformer';
import { ApiProperty } from '@nestjs/swagger';
import { IsString, MaxLength, MinLength } from 'class-validator';

export class JoinGroupDto {
  @ApiProperty({
    example: 'AB12CD34',
    minLength: 4,
    maxLength: 20,
    description: 'Join code generated by group admin'
  })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim().toUpperCase() : value))
  @IsString()
  @MinLength(4)
  @MaxLength(20)
  joinCode!: string;
}
